[package]
edition      = "2024"
name         = "sailing-instrument"
rust-version = "1.95"
version      = "0.1.0"

[[bin]]
name = "sailing-instrument"
path = "./src/bin/main.rs"

[dependencies]
esp-hal = { version = "~1.2.2", features = ["esp32s3", "unstable"] }
esp-bootloader-esp-idf = { version = "0.6.0", features = ["esp32s3"] }
critical-section = "1.2.0"
esp-backtrace = { version = "0.20.0", features = ["esp32s3", "panic-handler", "println"] }
esp-println = { version = "0.18.0", features = ["esp32s3"] }


# For fine tuning these settings, please refer to https://doc.rust-lang.org/cargo/reference/profiles.html
[profile.dev]
# The default debug profile is too slow and too big for resource-constrained devices.
opt-level = "s"       # Always build with some optimizations enabled.
codegen-units = 1     # LLVM can perform better optimizations using a single thread
debug         = 0     # none
lto           = 'fat'

[profile.release]
codegen-units = 1     # LLVM can perform better optimizations using a single thread
debug         = 0     # none
lto           = 'fat'
opt-level     = 's'
